// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBks-U0ioaB2vHzflfalQUDou6hnxfkZl4',
    appId: '1:389893666974:web:0ed6c01661240b7e23638f',
    messagingSenderId: '389893666974',
    projectId: 'passmate-a5cdd',
    authDomain: 'passmate-a5cdd.firebaseapp.com',
    storageBucket: 'passmate-a5cdd.appspot.com',
    measurementId: 'G-YPXKMN3D1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eMkP80WrurkWlp5BllqvDONXGz4Ac04',
    appId: '1:389893666974:android:ce839b2054032c8223638f',
    messagingSenderId: '389893666974',
    projectId: 'passmate-a5cdd',
    storageBucket: 'passmate-a5cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7pHOIBcOhUnRAPvQK1NvwmjHNPxvBOno',
    appId: '1:389893666974:ios:ab86cb30fcfccdf123638f',
    messagingSenderId: '389893666974',
    projectId: 'passmate-a5cdd',
    storageBucket: 'passmate-a5cdd.appspot.com',
    androidClientId:
        '389893666974-85i2eeq8eo4fb501oq52s2qhuq2m4mf4.apps.googleusercontent.com',
    iosClientId:
        '389893666974-c80qi8o4b8pmlrbfi2ir89mtct1ejjtc.apps.googleusercontent.com',
    iosBundleId: 'com.mates.passmate',
  );
}
